apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-conf-v1
  labels:
    app: conf-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conf-server-app
  template:
    metadata:
      labels:
        app: conf-server-app
    spec:
      containers:
        - name: conf-server-app
          image: conf-server-img
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: conf-service
spec:
  type: ClusterIP
  selector:
    app: conf-server-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conf-ingress
spec:
  rules:
    - host: "conf-server.local"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kuber-service-v1
                port:
                  number: 80
          - pathType: Prefix
            path: /test2
            backend:
              service:
                name: conf-service
                port:
                  number: 8080